package io.github.rdlopes.tfhe.core.ffm;

import io.github.rdlopes.tfhe.core.ffm.FheOps.*;

import java.lang.foreign.MemorySegment;
import java.util.function.Function;

/// Typed holder of method references for one FHE encrypted type.
///
/// Each field holds a method reference to a `TfheHeader` static wrapper
/// method, which itself delegates to a `static final MethodHandle`
/// (a `Linker.nativeLinker().downcallHandle(…)` result generated by
/// jextract). Method references are resolved via `invokedynamic` at
/// class-initialisation time and stored as immutable record fields — zero
/// runtime overhead at call time.
///
/// One instance per concrete type, stored in a `static final` field.
/// Handles are grouped into nested records by logical category to keep
/// construction readable.
///
/// @param <V> the Java clear-text type (e.g. `Byte`, `Short`, …)
public record FheTypeHandles<V>(
    FheValueKind<V>  valueKind,
    Lifecycle        lifecycle,
    Encryption<V>    encryption,
    Logic<V>         logic,
    Equality<V>      equality,
    Comparison<V>    comparison,
    Arithmetic<V>    arithmetic,
    Bitwise<V>       bitwise,
    Misc             misc
) {

  // ══════════════════════════════════════════════════════════════════════════
  // Nested handle groups
  // ══════════════════════════════════════════════════════════════════════════

  /// Lifecycle operations: destroy, clone, compress, serialize, deserialize.
  ///
  /// @param destroy     `(ptr) → int`  — passed to `NativePointer`
  /// @param clone_      `(input*, result**) → int`
  /// @param compress    `(input*, result**) → int`
  /// @param serialize   `(self*, buffer*, maxSize) → int`
  /// @param deserialize `(buffer*, maxSize, serverKey*, result**) → int`
  public record Lifecycle(
      Function<MemorySegment, Integer> destroy,
      UnaryOp    clone_,
      UnaryOp    compress,
      SerializeOp serialize,
      DeserializeOp deserialize
  ) {}

  /// Encryption and decryption operations.
  ///
  /// `encryptClientKey`, `encryptPublicKey`, `encryptTrivial`
  /// are `null` for wide types; `encryptWide*` are `null`
  /// for primitive types.
  public record Encryption<V>(
      EncryptPrimitiveOp<V>    encryptClientKey,
      EncryptPrimitiveOp<V>    encryptPublicKey,
      TrivialEncryptOp<V>      encryptTrivial,
      EncryptWideOp            encryptWideClientKey,
      EncryptWideOp            encryptWidePublicKey,
      TrivialEncryptWideOp     encryptWideTrivial,
      DecryptPrimitiveOp       decryptPrimitive,
      DecryptWideOp            decryptWide
  ) {}

  /// Bitwise logic operations (and, or, xor, not).
  public record Logic<V>(
      BinaryOp         bitAnd,
      BinaryOp         bitOr,
      BinaryOp         bitXor,
      UnaryOp          bitNot,
      AssignOp         bitAndAssign,
      AssignOp         bitOrAssign,
      AssignOp         bitXorAssign,
      ScalarOp<V>      scalarBitAnd,
      ScalarOp<V>      scalarBitOr,
      ScalarOp<V>      scalarBitXor,
      ScalarAssignOp<V> scalarBitAndAssign,
      ScalarAssignOp<V> scalarBitOrAssign,
      ScalarAssignOp<V> scalarBitXorAssign
  ) {}

  /// Equality comparisons (eq, ne).
  public record Equality<V>(
      BinaryOp    eq,
      BinaryOp    ne,
      ScalarOp<V> scalarEq,
      ScalarOp<V> scalarNe
  ) {}

  /// Ordering comparisons (lt, le, gt, ge) and min/max.
  public record Comparison<V>(
      BinaryOp    lt,
      BinaryOp    le,
      BinaryOp    gt,
      BinaryOp    ge,
      BinaryOp    min,
      BinaryOp    max,
      ScalarOp<V> scalarLt,
      ScalarOp<V> scalarLe,
      ScalarOp<V> scalarGt,
      ScalarOp<V> scalarGe,
      ScalarOp<V> scalarMin,
      ScalarOp<V> scalarMax
  ) {}

  /// Arithmetic operations.
  /// `abs` is `null` for unsigned types.
  public record Arithmetic<V>(
      BinaryOp         add,
      BinaryOp         sub,
      BinaryOp         mul,
      BinaryOp         div,
      BinaryOp         rem,
      CheckedOp        overflowingAdd,
      CheckedOp        overflowingSub,
      CheckedOp        overflowingMul,
      CheckedOp        divRem,
      AssignOp         addAssign,
      AssignOp         subAssign,
      AssignOp         mulAssign,
      AssignOp         divAssign,
      AssignOp         remAssign,
      ScalarOp<V>      scalarAdd,
      ScalarOp<V>      scalarSub,
      ScalarOp<V>      scalarMul,
      ScalarOp<V>      scalarDiv,
      ScalarOp<V>      scalarRem,
      ScalarAssignOp<V> scalarAddAssign,
      ScalarAssignOp<V> scalarSubAssign,
      ScalarAssignOp<V> scalarMulAssign,
      ScalarAssignOp<V> scalarDivAssign,
      ScalarAssignOp<V> scalarRemAssign,
      ScalarCheckedOp<V> scalarDivRem,
      UnaryOp          neg,
      UnaryOp          abs,
      ILog2Op          ilog2,
      CheckedILog2Op   checkedIlog2
  ) {}

  /// Bitwise shift and rotation operations.
  public record Bitwise<V>(
      BinaryOp    shl,
      BinaryOp    shr,
      BinaryOp    rotateLeft,
      BinaryOp    rotateRight,
      AssignOp    shlAssign,
      AssignOp    shrAssign,
      AssignOp    rotateLeftAssign,
      AssignOp    rotateRightAssign,
      ScalarOp<V> scalarShl,
      ScalarOp<V> scalarShr,
      ScalarOp<V> scalarRotateLeft,
      ScalarOp<V> scalarRotateRight,
      ScalarAssignOp<V> scalarShlAssign,
      ScalarAssignOp<V> scalarShrAssign,
      ScalarAssignOp<V> scalarRotateLeftAssign,
      ScalarAssignOp<V> scalarRotateRightAssign,
      UnaryOp     leadingOnes,
      UnaryOp     leadingZeros,
      UnaryOp     trailingOnes,
      UnaryOp     trailingZeros
  ) {}

  /// Random generation and if-then-else.
  public record Misc(
      RandomOp        random,
      RandomBoundedOp randomBounded,
      IfThenElseOp    ifThenElse
  ) {}
}
