name: CI/CD

env:
  JAVA_VERSION: '24'
  JAVA_DISTRIBUTION: 'temurin'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Download jextract
        run: curl https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz --output jextract.tar.gz
      - name: Decompress jextract
        uses: somaz94/compress-decompress@v1
        with:
          command: decompress
          source: jextract.tar.gz
          format: tgz
      - name: Test jextract presence
        run: |
          export PATH=$PATH:./jextract-22/bin
          jextract --help

      - name: Build with Maven
        run: |
          export PATH=$PATH:./jextract-22/bin
          mvn package

      - name: Live documentation with Maven
        run: mvn verify
