name: Native Libraries Bundle

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:

  native-libs:
    name: Build Native Libraries
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - run: gh repo clone zama-ai/tfhe-rs .
        env:
          GH_TOKEN: ${{github.token}}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ${{matrix.os}}
      - run: make build_c_api
      - run: cp tfhe/LICENSE target/release
      - name: Upload Native Libraries
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{matrix.os}}
          path: target/release
          retention-days: 1

  bundle-native-libs:
    name: Bundle Native Libraries
    runs-on: ubuntu-latest
    needs: native-libs
    steps:
      - name: Download Native Libraries
        uses: actions/download-artifact@v5
        with:
          pattern: 'native-libs-*'
          merge-multiple: 'true'
          path: native-libs
          github-token: ${{github.token}}
      - name: Pack OSX Library
        run: |
          mkdir -p native-bundle/libs/osx/aarch64
          cp native-libs/tfhe.h native-bundle/libs/osx/aarch64
          cp native-libs/*.dylib native-bundle/libs/osx/aarch64
      - name: Pack Linux Library
        run: |
          mkdir -p native-bundle/libs/linux/x86_64
          cp native-libs/tfhe.h native-bundle/libs/linux/x86_64
          cp native-libs/*.so native-bundle/libs/linux/x86_64
      - name: Pack Windows Library
        run: |
          mkdir -p native-bundle/libs/windows/x86_64
          cp native-libs/tfhe.h native-bundle/libs/windows/x86_64
          cp native-libs/*.dll native-bundle/libs/windows/x86_64
      - run: cp native-libs/LICENSE native-bundle/libs
      - uses: jcwillox/install-tool-action@v1
        with:
          id: 'jextract'
          download_url: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
          version: '22+6-47'
          bin_path: 'jextract-22/bin'
      - name: Jextract Dump includes
        run: |
          jextract native-libs/tfhe.h \
          --dump-includes jextract-includes.txt
      - name: Jextract filter Includes
        run: |
          grep tfhe jextract-includes.txt > jextract-includes-filtered.txt
          cat jextract-includes-filtered.txt
      - name: Jextract Bindings
        run: |
          mkdir -p .native/bindings
          jextract native-libs/tfhe.h \
          @jextract-includes-filtered.txt \
          --header-class-name TfheHeader \
          --target-package io.github.rdlopes.tfhe.ffm \
          --output native-bundle/bindings
      - name: Upload Native Libraries Bundle
        uses: actions/upload-artifact@v4
        with:
          name: native-bundle
          path: native-bundle
          retention-days: 1
      - name: Delete Native Libraries Specific Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: 'native-libs-*'

