name: Native Libraries Bundle

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:

  native-libs:
    name: Build Native Libraries
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - run: gh repo clone zama-ai/tfhe-rs .
        env:
          GH_TOKEN: ${{github.token}}
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache-shared-key: ${{matrix.os}}
      - run: make build_c_api
      - run: cp tfhe/LICENSE target/release
      - name: Upload Native Libraries
        uses: actions/upload-artifact@v7
        with:
          name: native-libs-${{matrix.os}}
          path: target/release
          retention-days: 1

  bundle-native-libs:
    name: Bundle Native Libraries
    runs-on: ubuntu-latest
    needs: native-libs
    steps:
      - uses: actions/checkout@v6
      - name: Download Native Libraries
        uses: actions/download-artifact@v8
        with:
          pattern: 'native-libs-*'
          merge-multiple: 'true'
          path: native-libs
          github-token: ${{github.token}}
      - name: Pack OSX Library
        run: |
          mkdir -p native-bundle/libs/osx/aarch_64
          cp native-libs/tfhe.h native-bundle/libs/osx/aarch_64
          cp native-libs/*.dylib native-bundle/libs/osx/aarch_64
      - name: Pack Linux Library
        run: |
          mkdir -p native-bundle/libs/linux/x86_64
          cp native-libs/tfhe.h native-bundle/libs/linux/x86_64
          cp native-libs/*.so native-bundle/libs/linux/x86_64
      - name: Pack Windows Library
        run: |
          mkdir -p native-bundle/libs/windows/x86_64
          cp native-libs/tfhe.h native-bundle/libs/windows/x86_64
          cp native-libs/*.dll native-bundle/libs/windows/x86_64
      - run: cp native-libs/LICENSE native-bundle/libs
      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Generate Bindings
        run: |
          java build-support/BuildNative.java --only-bindings --header native-libs/tfhe.h --output native-bundle/bindings
      - name: Upload Native Libraries Bundle
        uses: actions/upload-artifact@v7
        with:
          name: native-bundle
          path: native-bundle
          retention-days: 30
      - name: Delete Native Libraries Specific Artifacts
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: 'native-libs-*'

