name: Native Libraries Bundle

on:
  push:
    branches:
      - main

concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:

  native-libs:
    strategy:
      matrix:
        include:
          - os: macos-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_macos-aarch64_bin.tar.gz
            output: native-libs/osx/aarch64
          - os: ubuntu-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
            output: native-libs/linux/x86_64
          - os: windows-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_windows-x64_bin.tar.gz
            output: native-libs/windows/x86_64
    runs-on: ${{matrix.os}}
    steps:
      - run: gh repo clone zama-ai/tfhe-rs .
        env:
          GH_TOKEN: ${{github.token}}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ${{matrix.os}}
      - run: make build_c_api
      - name: Upload Native Libraries
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{matrix.os}}
          path: target/release
          retention-days: 1

  bindings:
    runs-on: ubuntu-latest
    needs: native-libs
    steps:
      - uses: jcwillox/install-tool-action@v1
        with:
          id: 'jextract'
          download_url: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
          version: '22+6-47'
          bin_path: 'jextract-22/bin'
      - name: Download Linux Libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libs-ubuntu-latest
          github-token: ${{github.token}}
      - name: Jextract Dump includes
        run: |
          jextract \
          --dump-includes jextract-includes.txt \
          tfhe.h
      - name: Jextract filter Includes
        run: |
          grep tfhe jextract-includes.txt > jextract-includes-filtered.txt
          cat jextract-includes-filtered.txt
      - name: Jextract Bindings
        run: |
          jextract \
          @jextract-includes-filtered.txt \
          --header-class-name TfheNative \
          --target-package ai.zama.tfhe \
          --output native-bindings \
          --use-system-load-library \
          --include-dir . \
          --include-dir deps \
          --library tfhe \
          tfhe.h
      - name: Upload FFM Bindings
        uses: actions/upload-artifact@v4
        with:
          name: native-bindings
          path: native-bindings

  bundle-native-libs:
    runs-on: ubuntu-latest
    needs: bindings
    steps:
      - name: Download Native Libraries
        uses: actions/download-artifact@v4
        with:
          pattern: 'native-libs-*'
          merge-multiple: 'true'
          path: native-libs
          github-token: ${{github.token}}
      - name: Pack OSX Library
        run: |
          mkdir -p native-bundle/osx/aarch64
          cp native-libs/tfhe.h native-bundle/osx/aarch64
          cp native-libs/*.dylib native-bundle/osx/aarch64
      - name: Pack Linux Library
        run: |
          mkdir -p native-bundle/linux/x86_64
          cp native-libs/tfhe.h native-bundle/linux/x86_64
          cp native-libs/*.so native-bundle/linux/x86_64
      - name: Pack Windows Library
        run: |
          mkdir -p native-bundle/windows/x86_64
          cp native-libs/tfhe.h native-bundle/windows/x86_64
          cp native-libs/*.dll native-bundle/windows/x86_64
      - name: Upload Native Libraries Bundle
        uses: actions/upload-artifact@v4
        with:
          name: native-libs
          path: native-bundle
      - name: Delete Native Libraries Specific Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: 'native-libs-*'

