name: Native Libraries Bundle

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  bindings:
    strategy:
      matrix:
        include:
          - os: macos-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_macos-aarch64_bin.tar.gz
            classifier: osx-aarch_64
          - os: ubuntu-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
            classifier: linux-x86_64
          - os: windows-latest
            jextract: https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_windows-x64_bin.tar.gz
            classifier: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jcwillox/install-tool-action@v1
        with:
          id: 'jextract'
          download_url: ${{ matrix.jextract }}
          version: '22+6-47'
          bin_path: 'jextract-22/bin'

      - run: gh repo clone zama-ai/tfhe-rs .
        env:
          GH_TOKEN: ${{github.token}}
      - run: make build_c_api

      - name: Jextract Dump includes
        run: |
          jextract \
          --dump-includes jextract-includes.txt \
          target/release/tfhe.h
      - name: Jextract filter Includes
        run: grep tfhe jextract-includes.txt > jextract-includes-filtered.txt
      - name: Jextract Bindings
        run: |
          jextract \
          @jextract-includes-filtered.txt
          --header-class-name TfheNative \
          --target-package ai.zama.tfhe \
          --output bindings \
          --use-system-load-library \
          --include-dir target/release \
          --include-dir target/release/deps \
          --library tfhe \
          target/release/tfhe.h

      - name: Upload Bindings
        uses: actions/upload-artifact@v4
        with:
          name: native-bindings-${{ matrix.classifier }}
          path: target/release

  bundle:
    runs-on: ubuntu-latest
    needs: bindings
    steps:

      - name: Bundle Native Libraries
        uses: actions/upload-artifact/merge@v4
        with:
          name: 'native-bindings'
          pattern: 'native-bindings-*'
